# -*- coding: utf-8 -*-
"""listint_count.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yfEt2mqxj-JaYL5CVtZyvHIL0r5mM7i5
"""

def Count_dist(l1):

   d1 = {}
   for i in l1:
    d1[i] = l1.count(i)
   return d1
 

if __name__ == "__main__":
    list1 =list(map(int,input().split()))
    print(Count_dist(list1))